<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="5" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="TestSuitePraktikum4" duration-ms="32" started-at="2018-06-20T11:07:31Z" finished-at="2018-06-20T11:07:31Z">
    <groups>
      <group name="erwartetexception">
        <method signature="MessreiheTest.Mgrgl0_Zgrgl15_V_M()[pri:0, instance:test.MessreiheTest@6d00a15d]" name="Mgrgl0_Zgrgl15_V_M" class="test.MessreiheTest"/>
        <method signature="MessreiheTest.Mgrgl0_Zgrgl15_Vstrings_Mfalsch()[pri:0, instance:test.MessreiheTest@6d00a15d]" name="Mgrgl0_Zgrgl15_Vstrings_Mfalsch" class="test.MessreiheTest"/>
        <method signature="MessreiheTest.Mgrgl0_Zkl15_V_M()[pri:0, instance:test.MessreiheTest@6d00a15d]" name="Mgrgl0_Zkl15_V_M" class="test.MessreiheTest"/>
        <method signature="MessreiheTest.Mkl0_Zgrgl15_V_M()[pri:0, instance:test.MessreiheTest@6d00a15d]" name="Mkl0_Zgrgl15_V_M" class="test.MessreiheTest"/>
        <method signature="MessreiheTest.Mkl0_Zkl15_V_M()[pri:0, instance:test.MessreiheTest@6d00a15d]" name="Mkl0_Zkl15_V_M" class="test.MessreiheTest"/>
      </group> <!-- erwartetexception -->
    </groups>
    <test name="test" duration-ms="32" started-at="2018-06-20T11:07:31Z" finished-at="2018-06-20T11:07:31Z">
      <class name="test.MessreiheTest">
        <test-method status="PASS" signature="Mgrgl0_Zgrgl15_V_M()[pri:0, instance:test.MessreiheTest@6d00a15d]" name="Mgrgl0_Zgrgl15_V_M" duration-ms="9" started-at="2018-06-20T13:07:31Z" finished-at="2018-06-20T13:07:31Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Fehler bei der Erstellung des Konstruktors! Übergebener Parameter verbraucher ist als leerer String gesetzt!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Fehler bei der Erstellung des Konstruktors! Übergebener Parameter verbraucher ist als leerer String gesetzt!
	at business.Messreihe.<init>(Messreihe.java:26)
	at test.MessreiheTest.Mgrgl0_Zgrgl15_V_M(MessreiheTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Mgrgl0_Zgrgl15_V_M -->
        <test-method status="PASS" signature="Mgrgl0_Zgrgl15_Vstrings_Mfalsch()[pri:0, instance:test.MessreiheTest@6d00a15d]" name="Mgrgl0_Zgrgl15_Vstrings_Mfalsch" duration-ms="1" started-at="2018-06-20T13:07:31Z" finished-at="2018-06-20T13:07:31Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Fehler bei der Erstellung des Konstruktors!! Übergebener Parameter messgroesse ist mit den falschen Werten besetzt!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Fehler bei der Erstellung des Konstruktors!! Übergebener Parameter messgroesse ist mit den falschen Werten besetzt!
	at business.Messreihe.<init>(Messreihe.java:30)
	at test.MessreiheTest.Mgrgl0_Zgrgl15_Vstrings_Mfalsch(MessreiheTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Mgrgl0_Zgrgl15_Vstrings_Mfalsch -->
        <test-method status="PASS" signature="Mgrgl0_Zkl15_V_M()[pri:0, instance:test.MessreiheTest@6d00a15d]" name="Mgrgl0_Zkl15_V_M" duration-ms="0" started-at="2018-06-20T13:07:31Z" finished-at="2018-06-20T13:07:31Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Fehler bei der Erstellung des Konstruktors! Messreihen-ID ist mit den falschen Werten besetzt!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Fehler bei der Erstellung des Konstruktors! Messreihen-ID ist mit den falschen Werten besetzt!
	at business.Messreihe.<init>(Messreihe.java:19)
	at test.MessreiheTest.Mgrgl0_Zkl15_V_M(MessreiheTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Mgrgl0_Zkl15_V_M -->
        <test-method status="PASS" signature="Mkl0_Zgrgl15_V_M()[pri:0, instance:test.MessreiheTest@6d00a15d]" name="Mkl0_Zgrgl15_V_M" duration-ms="1" started-at="2018-06-20T13:07:31Z" finished-at="2018-06-20T13:07:31Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Fehler bei der Erstellung des Konstruktors! Messreihen-ID ist mit den falschen Werten besetzt!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Fehler bei der Erstellung des Konstruktors! Messreihen-ID ist mit den falschen Werten besetzt!
	at business.Messreihe.<init>(Messreihe.java:19)
	at test.MessreiheTest.Mkl0_Zgrgl15_V_M(MessreiheTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Mkl0_Zgrgl15_V_M -->
        <test-method status="PASS" signature="Mkl0_Zkl15_V_M()[pri:0, instance:test.MessreiheTest@6d00a15d]" name="Mkl0_Zkl15_V_M" duration-ms="1" started-at="2018-06-20T13:07:31Z" finished-at="2018-06-20T13:07:31Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Fehler bei der Erstellung des Konstruktors! Messreihen-ID ist mit den falschen Werten besetzt!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Fehler bei der Erstellung des Konstruktors! Messreihen-ID ist mit den falschen Werten besetzt!
	at business.Messreihe.<init>(Messreihe.java:19)
	at test.MessreiheTest.Mkl0_Zkl15_V_M(MessreiheTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Mkl0_Zkl15_V_M -->
      </class> <!-- test.MessreiheTest -->
    </test> <!-- test -->
  </suite> <!-- TestSuitePraktikum4 -->
</testng-results>
